version: "3.3"
services:
  sweeper:
    build: .
    command: ["wandb", "agent", "ptajman/min_pandl_1000_improving/lv9vgt5c"]
    volumes:
     - ./wandb:/job/wandb
    environment:
      WANDB_API_KEY: abc7a849d5def805be56001abf5129be68e0fa47
      WANDB_MODE: offline
